const { Pool } = require("pg");
const crypto = require("crypto");
const pool = process.env.DATABASE_URL ? new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.NODE_ENV==="production"?{rejectUnauthorized:false}:false,max:5}) : null;
const BASE="https://api.datamartgh.shop/api/developer";
const KEY=()=>String(process.env.DATAMART_API_KEY||"").trim();
const SECRET=()=>String(process.env.DATAMART_API_SECRET||"").trim();
const ref=()=> "DGM-MASHUP-"+Date.now().toString(36).toUpperCase()+"-"+crypto.randomBytes(3).toString("hex").toUpperCase();
async function dm(path,opts={}){if(!KEY()||!SECRET())throw Object.assign(new Error("DataMart is not configured."),{status:503});const c=new AbortController(),t=setTimeout(()=>c.abort(),30000);try{const r=await fetch(BASE+path,{...opts,signal:c.signal,headers:{"Content-Type":"application/json","X-API-Key":KEY(),"X-API-Secret":SECRET(),...(opts.headers||{})}});const txt=await r.text();let d={};try{d=txt?JSON.parse(txt):{}}catch{}if(!r.ok)throw Object.assign(new Error(d.message||d.error||d.code||("DataMart HTTP "+r.status)),{status:r.status,data:d});return d}finally{clearTimeout(t)}}
function login(req,res,next){if(!req.session?.customerId)return res.status(401).json({success:false,message:"Please login to continue."});next()}
function validMtn(phone){return /^0(?:24|54|55|59)\\d{7}$/.test(phone)}
async function refund(customerId,orderId,amount,orderRef,reason){const c=await pool.connect();try{await c.query("BEGIN");const oq=await c.query("SELECT status FROM orders WHERE id=$1 FOR UPDATE",[orderId]);if(!oq.rows.length||oq.rows[0].status==="Refunded"){await c.query("COMMIT");return false}const q=await c.query("SELECT balance FROM customers WHERE id=$1 FOR UPDATE",[customerId]);const before=Number(q.rows[0]?.balance||0),after=Math.round((before+amount)*100)/100;await c.query("UPDATE customers SET balance=$1 WHERE id=$2",[after,customerId]);await c.query("INSERT INTO wallet_transactions(customer_id,type,amount,balance_before,balance_after,description,transaction_ref,status,reference) VALUES($1,'Credit',$2,$3,$4,$5,$6,'Completed',$7)",[customerId,amount,before,after,"MTN MashUp refund - "+orderRef,"REFUND-"+orderRef,"DGM-MASHUP-REFUND-"+orderRef]);await c.query("UPDATE orders SET status='Refunded',provider_status='failed',provider_message=$1 WHERE id=$2",[reason,orderId]);await c.query("COMMIT");return true}catch(e){try{await c.query("ROLLBACK")}catch{}throw e}finally{c.release()}}
async function reconcilePending(){if(!pool||!KEY()||!SECRET())return;let rows=[];try{const q=await pool.query("SELECT id,customer_id,amount,order_ref,provider_reference FROM orders WHERE service='MTN MashUp' AND status='Processing' AND provider_status='pending' AND provider_reference IS NOT NULL ORDER BY id ASC LIMIT 25");rows=q.rows}catch(e){console.error("MashUp reconciliation query:",e);return}for(const o of rows){try{const d=await dm("/order-status/"+encodeURIComponent(o.provider_reference));const p=d?.data||d||{};const s=String(p.orderStatus||p.status||"pending").toLowerCase();if(["completed","success","successful"].includes(s)){await pool.query("UPDATE orders SET status='Completed',provider_status=$1,provider_message=$2 WHERE id=$3 AND status='Processing'",[p.orderStatus||"completed",p.message||"Completed",o.id])}else if(["failed","cancelled","canceled","refunded"].includes(s)){await refund(o.customer_id,o.id,Number(o.amount||0),o.order_ref,p.message||("DataMart status: "+s))}}catch(e){console.error("MashUp reconciliation:",o.order_ref,e.message)}}}
function startReconciliation(){if(!pool||!KEY()||!SECRET())return;setTimeout(()=>{reconcilePending().catch(()=>{});setInterval(()=>reconcilePending().catch(()=>{}),60000)},15000)}
function installMashup(app){startReconciliation();
 app.get("/api/mashup/packages",async(req,res)=>{try{return res.json(await dm("/mashup/packages"))}catch(e){return res.status(e.status||500).json({success:false,message:e.message,code:e.data?.code})}});
 app.post("/api/mashup/purchase",login,async(req,res)=>{
  const phone=String(req.body?.phone||"").replace(/\s+/g,""),comboCost=Number(req.body?.comboCost);
  if(!/^024\d{7}$/.test(phone))return res.status(400).json({success:false,message:"Enter a valid MTN number."});
  if(!Number.isInteger(comboCost)||comboCost<1)return res.status(400).json({success:false,message:"Invalid MashUp package."});
  let cat;try{cat=await dm("/mashup/packages")}catch(e){return res.status(e.status||500).json({success:false,message:e.message,code:e.data?.code})}
  if(cat?.open===false)return res.status(503).json({success:false,message:"MTN MashUp is temporarily unavailable.",code:"MASHUP_UNAVAILABLE"});
  const pack=(Array.isArray(cat?.data)?cat.data:[]).find(p=>Number(p.comboCost)===comboCost);if(!pack)return res.status(400).json({success:false,message:"That MashUp package is unavailable.",code:"UNKNOWN_PACKAGE"});
  const amount=Number(pack.price),orderRef=ref(),walletRef="DGM-MASHUP-"+orderRef,client=await pool.connect();
  try{await client.query("BEGIN");const cr=await client.query("SELECT id,balance FROM customers WHERE id=$1 FOR UPDATE",[req.session.customerId]);if(!cr.rows.length)throw Error("Customer account not found.");const c=cr.rows[0],before=Number(c.balance||0);if(before<amount){await client.query("ROLLBACK");return res.status(400).json({success:false,code:"INSUFFICIENT_WALLET_BALANCE",message:"Insufficient wallet balance.",balance:before,required:amount})}const after=Math.round((before-amount)*100)/100;await client.query("UPDATE customers SET balance=$1 WHERE id=$2",[after,c.id]);const or=await client.query(`INSERT INTO orders(order_ref,customer_id,service,network,phone,amount,status,capacity,payment_status,provider_status) VALUES($1,$2,'MTN MashUp','MTN_COMBO',$3,$4,'Processing',$5,'Paid','pending') RETURNING id,*`,[orderRef,c.id,phone,amount,String(pack.capacity||0)+"GB"]);await client.query(`INSERT INTO wallet_transactions(customer_id,type,amount,balance_before,balance_after,description,transaction_ref,status,reference) VALUES($1,'Debit',$2,$3,$4,$5,$6,'Completed',$7)`,[c.id,amount,before,after,"MTN MashUp - "+pack.title+" - "+phone,orderRef,walletRef]);await client.query("COMMIT");let d;try{d=await dm("/mashup/purchase",{method:"POST",body:JSON.stringify({phoneNumber:phone,comboCost,ref:orderRef})})}catch(e){await refund(c.id,or.rows[0].id,amount,orderRef,e.message||"MashUp purchase failed");return res.status(e.status&&e.status<500?e.status:502).json({success:false,message:e.message,refunded:true,code:e.data?.code})}const p=d?.data||{};await pool.query("UPDATE orders SET provider_reference=$1,provider_status=$2,provider_message=$3 WHERE id=$4",[p.reference||orderRef,p.orderStatus||"pending",p.message||"",or.rows[0].id]);return res.json({success:true,order:{...or.rows[0],status:"Processing"},package:pack,provider:p,balance:after})}catch(e){try{await client.query("ROLLBACK")}catch{}console.error("MashUp purchase:",e);return res.status(500).json({success:false,message:e.message||"MashUp purchase failed."})}finally{client.release()}
 });
}
module.exports={installMashup};